import os

def clear():
    os.system('cls' if os.name == 'nt' else 'clear')

# basics sdjraslkdrals;
def prints():
    clear()
    print("## 1. Print Statements (Output)")
    print("-" * 40)
    print("The 'print()' function displays text or variable values to the console.")
    print("Example 1: Basic text output")
    print('print("Hello, World!")')
    print("\nExample 2: Using f-strings (formatted string literals) for variables")
    print('name = "Alex"')
    print('age = 30')
    print('print(f"My name is {name} and I am {age} years old.")')
    input("\nPress Enter to return...")

def inputs():
    clear()
    print("## 2. Input & Variables")
    print("-" * 40)
    print("Variables store data, and 'input()' gets data from the user.")
    print("\nExample 1: Storing text input")
    print('user_name = input("What is your name? ")')
    print('print(f"Welcome, {user_name}!")')
    print("\nExample 2: Variables can be reassigned (mutable)")
    print('count = 5')
    print('count = count + 1 # count is now 6')
    print('print(count)')
    input("\nPress Enter to return...")

def escape_sequences():
    clear()
    print("## 3. Escape Sequences")
    print("-" * 40)
    print("Special character combinations used within strings, starting with a backslash (\\).")
    print("\n- '\\n': Newline (starts a new line)")
    print('print("Line 1\\nLine 2")')
    print("\n- '\\t': Tab (inserts horizontal space)")
    print('print("Column 1\\tColumn 2")')
    print("\n- '\\\"': Double Quote (allows a double quote inside a double-quoted string)")
    print('print("He said, \\"Hello.\\"")')
    input("\nPress Enter to return...")

def length():
    clear()
    print("## 4. Length (len() function)")
    print("-" * 40)
    print("The 'len()' function returns the number of items in an object, like a string or list.")
    print("\nExample 1: String length")
    print('text = "Python"')
    print('length = len(text)')
    print('print(length) # Output: 6')
    print("\nExample 2: Checking length in a condition")
    print('if len(password) < 8:')
    print('    print("Password too short.")')
    input("\nPress Enter to return...")

def evals():
    clear()
    print("## 5. Type Casting (Int, Str, Float) & Type()")
    print("-" * 40)
    print("Type casting converts data from one type to another (e.g., text to number).")
    print("\nExample 1: Converting string input to an integer")
    print('age_str = input("Your age: ") # Input is always a string')
    print('age_int = int(age_str) # Convert to integer')
    print('print(age_int + 5)')
    print("\nExample 2: Using 'type()' to check the data type")
    print('a = 10')
    print('print(type(a)) # Output: <class \'int\'>')
    print("\nNote: The 'eval()' function executes code from a string, use with caution!")
    input("\nPress Enter to return...")


# operators s;ladrkasl;dkr
def arithmetic():
    clear()
    print("## 6. Arithmetic Operators")
    print("-" * 40)
    print("Used for mathematical operations:")
    print("\n* `+` (Addition)")
    print("* `-` (Subtraction)")
    print("* `*` (Multiplication)")
    print("* `/` (Division - returns float)")
    print("* `//` (Floor Division - returns integer)")
    print("* `%` (Modulus/Remainder)")
    print("* `**` (Exponentiation)")
    print("\nExample:")
    print('print(10 % 3) # Output: 1 (The remainder of 10 divided by 3)')
    print('print(7 // 2) # Output: 3')
    input("\nPress Enter to return...")

def assignment():
    clear()
    print("## 7. Assignment Operators")
    print("-" * 40)
    print("Used to assign values to variables, often combining an operation.")
    print("\n- `=` : Simple assignment (x = 5)")
    print("- `+=`: Add AND assign (x += 3 is same as x = x + 3)")
    print("- `-=`: Subtract AND assign (x -= 1 is same as x = x - 1)")
    print("- `*=` : Multiply AND assign")
    print("\nExample:")
    print('money = 100')
    print('money += 50')
    print('print(money) # Output: 150')
    input("\nPress Enter to return...")

def comparison():
    clear()
    print("## 8. Comparison Operators")
    print("-" * 40)
    print("Used to compare two values, returning a Boolean (True or False).")
    print("\n- `==`: Equal to")
    print("- `!=`: Not equal to")
    print("- `>` : Greater than")
    print("- `<` : Less than")
    print("- `>=`: Greater than or equal to")
    print("- `<=`: Less than or equal to")
    print("\nExample:")
    print('print(5 == 5) # Output: True')
    print('print(10 < 8) # Output: False')
    input("\nPress Enter to return...")

def logical():
    clear()
    print("## 9. Logical Operators")
    print("-" * 40)
    print("Used to combine or modify conditional statements.")
    print("\n- `and`: Returns True if BOTH statements are True.")
    print("- `or` : Returns True if AT LEAST ONE statement is True.")
    print("- `not`: Reverses the result (True becomes False, and vice-versa).")
    print("\nExample:")
    print('is_hot = True')
    print('is_sunny = False')
    print('print(is_hot and is_sunny) # Output: False')
    print('print(not is_hot) # Output: False')
    input("\nPress Enter to return...")


# conditionals sahsahsadh
def if_elif_else():
    clear()
    print("## 10. If/Elif/Else")
    print("-" * 40)
    print("Executes code blocks based on whether a condition is True.")
    print("\nSyntax:")
    print('score = 85')
    print('if score >= 90:')
    print('    print("Grade A")')
    print('elif score >= 80: # Checked if the first condition was False')
    print('    print("Grade B")')
    print('else: # Runs if all preceding conditions were False')
    print('    print("Below B")')
    input("\nPress Enter to return...")

def nested():
    clear()
    print("## 11. Nested Conditionals")
    print("-" * 40)
    print("Putting one conditional statement inside another to handle more complex logic.")
    print("\nExample:")
    print('is_member = True')
    print('is_premium = True')
    print('if is_member:')
    print('    print("Access granted.")')
    print('    if is_premium: # Nested condition')
    print('        print("Premium features unlocked.")')
    print('    else:')
    print('        print("Standard features.")')
    input("\nPress Enter to return...")

def combining():
    clear()
    print("## 12. Combining Conditions (Using AND/OR)")
    print("-" * 40)
    print("Using logical operators (`and`, `or`) to check multiple conditions in one `if` statement.")
    print("\nExample 1 (AND): Requires both to be True")
    print('temperature = 25')
    print('is_raining = False')
    print('if temperature > 20 and not is_raining:')
    print('    print("Perfect picnic weather.")')
    print("\nExample 2 (OR): Requires at least one to be True")
    print('if day == "Saturday" or day == "Sunday":')
    print('    print("It\'s the weekend.")')
    input("\nPress Enter to return...")


# Loops drklsadjrlasd
def for_loops():
    clear()
    print("## 13. For Loops")
    print("-" * 40)
    print("Used for iterating over a sequence (like a list, tuple, dictionary, set, or string).")
    print("\nExample 1: Iterating over a list")
    print('fruits = ["apple", "banana", "cherry"]')
    print('for fruit in fruits:')
    print('    print(fruit)')
    print("\nExample 2: Iterating a set number of times (using range)")
    print('for i in range(3): # Will run for i = 0, 1, 2')
    print('    print(i)')
    input("\nPress Enter to return...")

def while_loops():
    clear()
    print("## 14. While Loops")
    print("-" * 40)
    print("Executes a set of statements repeatedly as long as a specified condition is True.")
    print("Be careful of infinite loops!")
    print("\nExample:")
    print('count = 0')
    print('while count < 3:')
    print('    print(f"Count: {count}")')
    print('    count += 1 # Crucial step to avoid infinite loop')
    input("\nPress Enter to return...")

def nested_loops():
    clear()
    print("## 15. Nested Loops")
    print("-" * 40)
    print("A loop placed inside the body of another loop.")
    print("The inner loop completes all its iterations for each iteration of the outer loop.")
    print("\nExample (Simple multiplication table):")
    print('for i in range(1, 3): # Outer loop (i=1, i=2)')
    print('    for j in range(1, 3): # Inner loop (j=1, j=2)')
    print('        print(f"{i} x {j} = {i*j}")')
    input("\nPress Enter to return...")

def loop_control():
    clear()
    print("## 16. Loop Control Statements")
    print("-" * 40)
    print("Used to change the execution flow of a loop.")
    print("\n- `break`: Stops the loop immediately.")
    print('for i in range(10):')
    print('    if i == 5:')
    print('        break # Loop stops at 5')
    print("\n- `continue`: Skips the current iteration and moves to the next one.")
    print('for i in range(5):')
    print('    if i == 2:')
    print('        continue # Skips printing 2')
    input("\nPress Enter to return...")


# Lists and functions skdrthnaslkdr
def lists():
    clear()
    print("## 17. Lists")
    print("-" * 40)
    print("Lists are ordered, changeable collections of items (can hold different data types). Defined with square brackets [].")
    print("\nExample 1: Creation and Indexing")
    print('my_list = ["A", "B", "C"]')
    print('print(my_list[0]) # Output: A (Lists are 0-indexed)')
    print("\nExample 2: Common methods")
    print('my_list.append("D") # Adds D to the end')
    print('my_list.remove("B")')
    print('print(my_list) # Output: [\'A\', \'C\', \'D\']')
    input("\nPress Enter to return...")

def functions():
    clear()
    print("## 18. Functions (Concept and Built-in)")
    print("-" * 40)
    print("A function is a block of code which only runs when it is called.")
    print("Python has many built-in functions, like `print()`, `len()`, and `input()`.")
    print("\nExample 1: Calling a function")
    print('result = len("example")')
    print('print(result)')
    print("\nExample 2: Functions can accept arguments (data passed to them)")
    print('print(max(10, 20, 5)) # max() is a built-in function')
    input("\nPress Enter to return...")

def defs():
    clear()
    print("## 19. Defining Functions (def)")
    print("-" * 40)
    print("The 'def' keyword is used to create (define) your own functions.")
    print("\nSyntax:")
    print('def greet(name):')
    print('    return f"Hello, {name}!" # return sends data back')
    print('\nCalling the function:')
    print('message = greet("Maria")')
    print('print(message) # Output: Hello, Maria!')
    input("\nPress Enter to return...")

def importing_random():
    clear()
    print("## 20. Importing Modules (The Random Module)")
    print("-" * 40)
    print("Modules are external Python files containing functions you can use.")
    print("The `import` statement makes a module accessible.")
    print("\nExample: Getting a random number")
    print('import random')
    print('dice_roll = random.randint(1, 6) # Generate random integer between 1 and 6')
    print('print(f"You rolled a {dice_roll}")')
    input("\nPress Enter to return...")

def dictionaries():
    clear()
    print("## 21. Dictionaries")
    print("-" * 40)
    print("Dictionaries are unordered, changeable collections of Key-Value pairs. Defined with curly braces {}.")
    print("\nExample 1: Creation and Access")
    print('person = {"name": "Jude", "age": 25}')
    print('print(person["name"]) # Accessing by key')
    print("\nExample 2: Adding/Changing items")
    print('person["city"] = "Manila" # Add a new key-value pair')
    print('person["age"] = 26 # Change the value of age')
    print('print(person)')
    input("\nPress Enter to return...")